### ISSUE TITLE
New architecture?

### ISSUE THREAD

**Issue by erikjoling** [justintadlock/abc#1]
I see you are using new architectual approaches. What are your reasons behind them? Are you going to elaborate on them somewhere/sometime? 

I'm enthousiastic to see this in a WordPress theme and I'm curious to learn more about it. It's good to see some evolvement in theme development.

**Comment by justintadlock** [comment]
I'll definitely be writing about things a bit and putting together a readme at some point.  Right now, some of this is a bit experimental.  However, it's all based on an ongoing discussion on the Theme Hybrid Slack (must be a standard or premium member for access).  There's a lot of ground we've covered in the past month or so.  In fact, I'm still reading through a backlog of links from other developers there who've shared stuff.

Essentially, the idea is to modernize PHP, CSS, and JS for theme developers while also balancing that with "the WordPress way" a bit.

For example, I could've went with Twig, Blade, or Plates (what I originally had) for templating, but that's a bit of a foreign concept for many.  Still, there are steps we can take to _evolve_ templating somewhat.  And, that's what the `View` and `Wrapper` classes are about.

I feel pretty good about that aspect of things.

What we're currently discussing in Slack are CSS build tools.  Much of this is likely going to be based on the Post CSS project.

**Comment by erikjoling** [comment]
> it's all based on an ongoing discussion on the Theme Hybrid Slack

Thank you, I'll catch up with that

**Comment by justintadlock** [comment]
Just closing this out. Feel free to open new tickets if need be.
