### ISSUE TITLE
Text domain missing

### ISSUE THREAD

**Issue by samikeijonen** [justintadlock/abc#11]
Just adding this for reminder. Text domain is missing from strings: `__( 'Next &rarr;' )`.

**Comment by justintadlock** [comment]
Textdomains are intentionally left off throughout the entire theme.  We'll be using the `node-wp-i18n` package to allow theme authors to add textdomains and generate a POT file.

**Comment by justintadlock** [comment]
The following commands are now available:

```
// Auto-adds the textdomain.
npm run i18n:textdomain

// Creates POT file.
npm run i18n:pot

// Runs both of the above commands.
npm run i18n
```
