### ISSUE TITLE
before_page_number args to pagination

### ISSUE THREAD

**Issue by samikeijonen** [justintadlock/abc#13]
I was trying to add `before_page_number` to pagination like this:

```php
posts_pagination( [
	'prev_text'          => __( '&larr; Previous', 'uuups' ),
	'next_text'          => __( 'Next &rarr;', 'uuups' ),
	'title_text'         => __( 'Posts Navigation', 'uuups' ),
	'container_class'    => 'pagination pagination--posts',
	'title_class'        => 'pagination__title screen-reader-text',
	'before_page_number' => '<span class="meta-nav screen-reader-text">' . __( 'Page', 'uuups' ) . ' </span>',
] );
```

But it outputs:

```php
<li class="pagination__item pagination__item--number"><a href="http://foxland-products.local/page/2/" class="pagination__anchor pagination__anchor--link">&lt;span class="meta-nav screen-reader-text"&gt;Page </a></li>
```

I'm not sure where the escaping function kicks in for `&lt;span`.

**Comment by justintadlock** [comment]
The link is broken down into parts.  And, the link text is later added back on output and wrapped with `esc_html()`.

I'm going to hold off on changing this right at this time because I have another helper function that I've been working on that may be a better choice than the current code.

**Comment by justintadlock** [comment]
This is broken in Hybrid Core, but I'm going to leave this ticket open for reference.

**Comment by justintadlock** [comment]
This should be fixed now.
