### ISSUE TITLE
Production?

### ISSUE THREAD

**Issue by Skaldical** [justintadlock/abc#15]
@justintadlock 

I love the direction this theme is going. I realize it is under very active development right now, but do you have an idea of when you think it would be stable enough for production use?

I'd like to take my first stab at developing with the "hybrid suite" and I'm not sure what direction to go in terms of the starter themes you've developed.

Thanks so much!

**Comment by justintadlock** [comment]
I'd like to have something in May, but it's really too early to say right now.

**Comment by Skaldical** [comment]
Got it! I'll get my feet wet with the stable starter theme first (I'm a paid subscriber :) )Thanks for your innovation with this. Looking forward to seeing where it goes.

**Comment by justintadlock** [comment]
I now have a more definitive answer to this question.  We're shooting for an August 5 release date.  This is to commemorate the 10th anniversary of ThemeHybrid.com.

Original site launch post: https://themehybrid.com/weblog/welcome-to-theme-hybrid

I can't guarantee it'll be 1.0, but I'm at least shooting for a beta or release candidate at that point that should be stable enough to run in production.

With the above said, I believe a few of the devs helping with this are already incorporating it into some projects.
