### ISSUE TITLE
Description markup is show even if it's empty

### ISSUE THREAD

**Issue by samikeijonen** [justintadlock/abc#16]
Current markup: `<div class="app-header__description"><?php bloginfo( 'description' ) ?></div>`.

Should we roll a template function for this so that description is only shown when there is one. [Similar to Underscores](https://github.com/Automattic/_s/blob/master/header.php#L40).

I was thinking template function if we wan't to avoid `if else` as much as possible in template files.

**Comment by justintadlock** [comment]
I might bring back the `hybrid_site_description()` function that was in HC.
