### ISSUE TITLE
viewBox is removed from SVGs

### ISSUE THREAD

**Issue by samikeijonen** [justintadlock/abc#25]
`viewBox` should not be removed when running `npm run build`. `viewBox` is needed for consistent styling.

Just leaving the notice here, debug later.

**Comment by samikeijonen** [comment]
[`removeviewBox: false` worked for me](https://github.com/samikeijonen/uuups/commit/186391a50d7e3d8ad44ba155dad1b419d0539387#diff-31429536feed8ddd15c8ece5a0eba0d1R180).

**Comment by m-e-h** [comment]
Some others I've found useful
```
imagemin.svgo({
					plugins: [
						{ cleanupIDs: true },
						{ removeTitle: true },
						{ removeViewBox: false },
						{ removeAttrs: { attrs: "(fill|stroke)" } },
						{ addClassesToSVGElement: { className: "v-icon" } },
						{ removeUselessStrokeAndFill: true },
						{ cleanupNumericValues: { floatPrecision: 2 } },
						{ removeNonInheritableGroupAttrs: true },
						{ removeDimensions: true }
					]
				})
```

**Comment by justintadlock** [comment]
This should be correct in the latest.
